"""empty message

Revision ID: d6dbbb587997
Revises: 
Create Date: 2019-01-03 22:28:02.649331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6dbbb587997'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codeRecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=True),
    sa.Column('code_nums', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codeRecord')
    op.drop_table('user')
    # ### end Alembic commands ###
